['custom-branding']
appName = "YouTube"

['custom-video-speed']
granularity = "16"
min = "0.25"
max = "2.5"

['enable-android-debugging']
debuggable = false

['spotify-theme']
backgroundColor = "@android:color/black"
accentColor = "#ff1ed760"
accentPressedColor = "#ff169c46"

[theme]
darkThemeBackgroundColor = "@android:color/black"
lightThemeBackgroundColor = "@android:color/white"
darkThemeSeekbarColor = "#ffff0000"
